### PR TITLE
move CoBlocks menu page to Tools

### LINKED ISSUE #739: Move CoBlocks top-level admin menu item
**Is this enhancement related to a problem? Please describe.**
The `CoBlocks` top-level menu item does not need to be top-level, as the plugin does not require any sub items. It's great as the page contains introduction text and a couple videos (which we can extend in the future to more even), but it should not be top-level.

**Describe the solution you'd like**
Move the `CoBlocks` top-menu item to an existing sub menu, perhaps `Tools`?

**Describe alternatives you've considered**
We have a filter in place (which can remain) but this isn't a great option for less-developer-oriented folks. 

**Additional context**
Screen Shot 2019-08-14 at 11 06 02 AM

### PR DESCRIPTION
**Pull request by paranoia1906**
Note: Reasons for this location are listed at https://github.com/godaddy/coblocks/issues/739#issuecomment-521761820

- Closes #739

### CODE REVIEW

**Comment by paranoia1906** [comment]
Not positive why the test is failing. Going to get another look later. If anyone spots the issue please advise.

**Comment by richtabor** [comment]
@EvanHerman do you mind helping Anthony get the test passing? Thanks!

**Comment by EvanHerman** [comment]
@paranoia1906 @richtabor I wrote up a small explanation as to why this is failing in Slack a little while ago: https://godaddy.slack.com/archives/GKQGZCGK1/p1565902254089900

With the steps I've outlined there, the tests should start passing 👍 

We'll also want to write a new test for the new `coblocks_getting_started_submenu_parent_slug` filter.

**Comment by paranoia1906** [comment]
Fixed unittest related to the CoBlocks menu page.

**Pull request merged**
