### PR TITLE
ISBAT have consistent component styling in WordPress 5.3

### LINKED ISSUE #1052: Inconsistent component styling for WordPress 5.3
**Describe the bug**
Default/actives states in our custom controls are no longer styled appropriately with the new flat/blue styles coming into Gutenberg in WordPress 5.3. 

**Screenshots**
Screen Shot 2019-10-22 at 6 50 05 AM
Screen Shot 2019-10-22 at 6 54 12 AM
Screen Shot 2019-10-22 at 6 54 30 AM
Screen Shot 2019-10-22 at 6 55 02 AM

**Expected behavior**
Custom controls with flat dark active states should be using the blue background as the new Publish/Update button does. 

Example of an appropriate default state:
Screen Shot 2019-10-22 at 6 53 29 AM

Here's an example of an active state within the Image block: 
Screen Shot 2019-10-22 at 6 51 15 AM

### PR DESCRIPTION
**Pull request by paranoia1906**
- Closes #1052 

Adjust styling for Dimensions Control components so that they resemble core style. By removing color specificity, core is able to set the color scheme.

I will review all components UI to look for changes needed for 5.3

- [ ] Dimensions Control (previously handled in #1087) 
- [ ] Crop Settings
- [x] Font Family
- [x] Grid Control
- [x] Size Control
- [x] Typography Control
- [x] Background
- [X] Responsive Tabs Control

### CODE REVIEW

**Comment by paranoia1906** [comment]
Changed CSS for components to use less color specificity colors should be provided from GB/core. 

Inspiration for changes came from https://github.com/WordPress/gutenberg/blob/master/packages/components/src/button/style.scss

**Comment by paranoia1906** [comment]
A few components have the new style in 5.2.4 when GB is not active. Those are the Dimensions Controls, Responsive Tabs Controls, and Grid Controls. The other components correctly inherit the color from core/GB.

**Comment by paranoia1906** [comment]
image

image

image

**Comment by richtabor** [comment]
@paranoia1906 let's do one more quick run-through to make sure we've got them all. Then it's good for merge.

**Comment by paranoia1906** [comment]
Looks good **with** and **without** GB running. 
Looks good **with** 5.3 RC4 and 5.2.4.

**Pull request merged**
