### PR TITLE
Add new category for gallery blocks

### PR DESCRIPTION
**Pull request by richtabor**
This is an experimental PR for #581 that adds a new "Gallery Blocks" category to the block inserter. 

**Screenshot:**
ScreenFlow

### CODE REVIEW

**Comment by fjarrett** [comment]
@richtabor Personally, I prefer this category approach over #592

**Comment by EvanHerman** [comment]
@richtabor @fjarrett I'm also a fan of this approach over the other. I wonder if we should re-name the category to something like `CoBlocks Gallery Blocks` so the two categories `CoBlocks` and `CoBlocks Gallery Blocks` live next to each other.

**Comment by EvanHerman** [comment]
Also, just another thought...isn't `CoBlocks Gallery Blocks` a little redundant since everything in that block inserter window are blocks.

**Comment by richtabor** [comment]
> Also, just another thought...isn't `Gallery Blocks` a little redundant since everything in that block inserter window are blocks.

I agree, the pattern is sort of disjointed in core. Perhaps ‘CoBlocks Galleries’ would work better?

**Comment by richtabor** [comment]
Here's another pass, with the CoBlocks categories displaying right after each other. I like this much better. Thoughts @fjarrett, @jrtashjian, @EvanHerman, @gmays? 

ScreenFlow

**Comment by fjarrett** [comment]
:100:

**Pull request merged**
