### PR TITLE
Hide avatar placeholder on Author block when not in use

### LINKED ISSUE #1050: ISNBAT see the Author block avatar placeholder if I'm not adding an avatar
**Is this enhancement related to a problem? Please describe.**
I am presented with an avatar placeholder, even though I may not have any intentions of adding an avatar to the Author block.

**Describe the solution you'd like**
If there is no avatar, and I am not selected on the block, the avatar placeholder should not be visible. I may still however drop an image into the Author block's dropZone, to add one. 

This is actually already how the front-end works.

### PR DESCRIPTION
**Pull request by AnthonyLedesma**
Closes #1050 

AuthorBlockImagePlaceholder

An issue here is that the child block `core/button` does not store a prop of `isSelected`. Reading props by using the following: 
```javascript
const childButton = wp.data.select( 'core/block-editor' ).getBlocksByClientId( clientId )[ 0 ].innerBlocks[ 0 ];
```

Any ideas on how to conditionally show when the `core/button` is selected?

### CODE REVIEW

**Comment by paranoia1906** [comment]
Here is the updated behavior after implementing the suggested changes. 
authorBlockHidePlaceholderImage

**Comment by richtabor** [comment]
Currently the `dropZone` is not available unless there's an image already there - or it's selected. Let's make the `dropZone` available at all times.

**Comment by AnthonyLedesma** [comment]
@richtabor Made the suggested change. Now `dropZone` is available at all times. Also added the necessary logic to persist the image when it exists.

**Comment by richtabor** [comment]
@jrtashjian Mind taking another peek at this one? Thanks!

**Pull request merged**
