### PR TITLE
Add block movers to Pricing Table Items

### PR DESCRIPTION
**Pull request by richtabor**
This PR adds block movers back to the Pricing Table Items, so you would be able to move them around inside the Pricing Tables parent block - closing #1081 

The reason they were disabled originally is because of the way we have the `count` selected. We needed to lock the InnerBlocks template so that we could manipulate the nested block count. I added `updateTables` (derived from the core Columns block) so that we could have both. 

I'm also using the `__experimentalMoverDirection` prop for `InnerBlocks`, which falls back to `vertical` without support. 

tables

### CODE REVIEW

**Comment by jrtashjian** [comment]
I can't seem to see these new movers. I tried the latest version of WordPress with Gutenberg 6.8.0 as well as the nightly build of WordPress (5.4-alpha-46674). The `__experimentalMoverDirection` is being detected by React Inspector Tools in Chrome.

Screen Shot 2019-11-07 at 5 49 26 PM

Screen Shot 2019-11-07 at 5 45 35 PM

**Comment by jrtashjian** [comment]
Looks like we have an odd behavior when removing the `templateLock`:

Kapture 2019-11-07 at 17 53 48

**Comment by richtabor** [comment]
@jrtashjian are you sure you built the files?

**Comment by richtabor** [comment]
Ah, it looks like `__experimentalMoverDirection` is not available in Gutenberg 6.8 or WP 5.3 just yet. I added back templateLock, but only `insert`, which removes the "Remove Block" control from that popover - but still maintains the switching table count capability.

If all is good on your end, I'm good with merging this and then coming back around later when `__experimentalMoverDirection` is officially supported - even though the movers will be vertical.

**Pull request merged**
