### PR TITLE
fix DimensionsControl for Gutenberg 6.2 and 6.3

### LINKED ISSUE #730: DimensionsControl breaks with Gutenberg 6.3.0
**Describe the bug**
The display of the DimensionsControl component is breaking when the Gutenberg 6.2.0 plugin is active. This applies to all blocks that use the DimensionsControl component.
`Row Block`
`Hero Block`
`Media Card Block`

**To Reproduce**

1. 'Add any effected component'
2. 'Access block settings inspector`

**Screenshots**
### Gutenberg Deactivated
image

image

image

### Gutenberg Activated
image

image

image

**Expected behavior**

**Isolating the problem:**
Mark completed items with an [x].

-   [ ] This bug happens with no other plugins activated
-   [X] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [X] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.2.2
**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
6.2.0

### PR DESCRIPTION
**Pull request by paranoia1906**
- Closes #730 

### Notes: 
This pull request switches from use of a button with popout to using a select element. Gutenberg made the same changes to their font-size-picker component with Gutenberg 6.2.0.

Styles added to handle display prior to Gutenberg merge into core WordPress. Those can be deprecated once core is merged with Gutenberg 6.2+. 

### Screenshot Of Fix
dimensionsControlFix

### CODE REVIEW

**Comment by richtabor** [comment]
Looking good @paranoia1906. 

> Styles added to handle display prior to Gutenberg merge into core WordPress. Those can be deprecated once core is merged with Gutenberg 6.2+.

The select element displays fine with and without Gutenberg installed. Is it still necessary to keep those styles or can we go ahead and remove?

**Comment by richtabor** [comment]
Let's reduce the space between the descriptive text and the selector, to match the select control (last in the screenshot). 

Screen Shot 2019-08-15 at 10 29 37 AM

**Comment by paranoia1906** [comment]
@richtabor. Good call on the spacing that should be no issue. 

image

Here is what the select elements look like when I remove the styles you are referencing here https://github.com/godaddy/coblocks/pull/741#issuecomment-521663606 This is with Gutenberg disabled.

**Comment by paranoia1906** [comment]
Spacing issue is resolved. @richtabor 

image

**Comment by paranoia1906** [comment]
Pushed one final fix to make the hidden screen reader label for the select items dynamic based on type of DimensionsControl.

**Comment by paranoia1906** [comment]
This pull request does **not** resolve the display issue for Icons block. Icons block does **not** use DimensionsControl component but **does** use the same classes for style. Would like to create a separate pull request to replace the functionality on Icons block.

**Comment by jrtashjian** [comment]
> Would like to create a separate pull request to replace the functionality on Icons block.

Please reference this PR in it once you do.

**Pull request merged**
