### PR TITLE
Fix Dynamic HR block display on TwentyTwenty

### PR DESCRIPTION
**Pull request by richtabor**
This PR is a test to see if we can inherit the core Separator's styling, so we wouldn't need to continue supporting individual styles. It's essentially a Separator + Spacer block combined. 

If we go this route we'll need to add a proper deprecation. 

A possible alternative to #1068.

### CODE REVIEW

**Comment by paranoia1906** [comment]
Added block deprecation. Experiencing an issue with setting text colors (hr divider colors) in twentytwenty theme. Found a few conflicts that should be addressed. 

**View in editor**
image

**View when published**
image

Issue seems to be conflicting styles from twentytwenty.

https://github.com/WordPress/twentytwenty/blob/dea9290e7ca3d38b7067c3b7107787db6554249a/style.css#L2591
```css
:root .has-accent-color {
	color: #cd2653;
}
```

https://github.com/WordPress/twentytwenty/blob/dea9290e7ca3d38b7067c3b7107787db6554249a/style.css#L419
```css
.entry-content hr:not(.has-background),
hr.styled-separator {
	color: #6d6d6d;
}
```

**Comment by jrtashjian** [comment]
> * Change markup to use a `div` instead of `hr` element.

@paranoia1906 What is the reason for this change? An HR is syntactically correct in this context.

**Comment by paranoia1906** [comment]
@jrtashjian The reason for the change in markup is detailed in this comment. 
https://github.com/godaddy/coblocks/pull/1079#issuecomment-547590928

Essentially, TwentyTwenty was overriding color settings simply because it was an `hr` element. I would love to know what type of alternative could be used there.

**Comment by richtabor** [comment]
We should stick to using `hr` here.

**Comment by jrtashjian** [comment]
I'm having difficulty understanding what we're trying to accomplish here or maybe just the method we're doing it. It sounds like we should just remove our Dynamic HR block and migrate over to the `core/separator` block. We can then add a new "blank" style to the `core/separator` block and add our height control to it.

This could be a nice test for how we remove support for certain blocks in preference of core blocks and even migrating block gallery blocks to the CoBlocks versions.

I suggest we close this PR and start a new one for enhancing the `core/separator` block.

**Comment by paranoia1906** [comment]
This request is closed in favor of https://github.com/godaddy/coblocks/pull/1093

**Pull request closed without merging**
